Don't run nmk-update when use git

diff --git a/bin/nmk-update b/bin/nmk-update
--- a/bin/nmk-update
+++ b/bin/nmk-update
@@ -1,7 +1,15 @@
 #!/bin/bash
 
+# note: this line call 3 external processes
+nmk_dir=$(dirname "$(dirname "$(readlink -f "$0")")")
+
+[ -d "$nmk_dir/.git" ] && echo ".git found, exit" && exit 1
+
 for python in "$NMK_PYTHON" python3 python; do
     # Call binary to determine python existence
     # Check binary existence doesn't work because pyenv provide python shims.
     "$python" --version > /dev/null 2>&1 && exec "$python" "$nmk_dir/bin/nmk-update.py" "$@"
 done
+
+>&2 echo "Error: Python not found"
+exit 1
